#!/bin/bash

# ==============================================================================
# Vast.ai Persistent Provisioning Script
# ==============================================================================
# This script installs Python packages to /workspace/python-packages to ensure
# they persist across instance restarts when the volume is mounted.
# It also configures Hugging Face cache to persist models on /workspace.
# Optimized to run only once (skips if already completed).
# ==============================================================================

set -e  # Exit on error

# ------------------------------------------------------------------------------
# 1. Configuration & Paths
# ------------------------------------------------------------------------------
PYTHON_DIR="/workspace/python-packages"
HF_CACHE_DIR="/workspace/huggingface_cache"
ENV_SETUP_SCRIPT="/workspace/env_setup.sh"
BASHRC_FILE="$HOME/.bashrc"
BUILD_FLAG="/workspace/.build_complete"
MODEL_DIR="$HF_CACHE_DIR/datalab-to/chandra"
CHANDRA_SERVER_SCRIPT="/workspace/chandra-vllm.sh"
# VLLM_API_SECRET="myscret" # should be passed on env vars during vast.ai build

if [ -f "$BUILD_FLAG" ]; then
    echo ">>> Build already done. Skipping."
else
    # ------------------------------------------------------------------------------
    # 2. Create Directories
    # ------------------------------------------------------------------------------
    # Clean the directories before installing to avoid orphaned packages/models
    rm -rf $PYTHON_DIR/
    rm -rf $HF_CACHE_DIR/ 

    echo ">>> Creating persistent directories..."
    mkdir -p $PYTHON_DIR
    mkdir -p $HF_CACHE_DIR

    # ------------------------------------------------------------------------------
    # 3. Install Python Packages
    # ------------------------------------------------------------------------------
    echo ">>> Installing packages to $PYTHON_DIR..."

    pip install --target=$PYTHON_DIR \
        --ignore-installed \
        --no-cache-dir \
        --index-url https://pypi.org/simple/   \
        --extra-index-url https://download.pytorch.org/whl/cu126   \
        torch==2.10.0+cu126 \
        torchaudio==2.10.0+cu126 \
        torchvision==0.25.0+cu126 \
        torchcodec==0.10.0 \
        torchdata==0.10.0 \
        torchtext==0.6.0 \
        torch_c_dlpack_ext==0.1.5 \
        pillow==12.1.0 \
        chandra-ocr==0.1.8 \
        huggingface_hub==0.36.2 \
        vllm==0.17.1
    echo ">>> Package installation complete. Flag file created."

    # ------------------------------------------------------------------------------
    # 4. Create Environment Setup Script
    # ------------------------------------------------------------------------------
    # This file lives on /workspace, so it persists across reboots.
    # It sets PYTHONPATH, PATH, and HF_HOME.
    # NOTE: pip --target installs scripts to the root of the target dir, NOT /bin
    # ------------------------------------------------------------------------------
    echo ">>> Creating environment setup script at $ENV_SETUP_SCRIPT..."
    cat > $ENV_SETUP_SCRIPT << EOF
# Auto-generated by provisioning_script.sh
# Persistent Environment Configuration

# 1. Python Packages Path
export PYTHONPATH=$PYTHON_DIR:\$PYTHONPATH
export PATH=$PYTHON_DIR:\$PATH

# 2. Hugging Face & Model Cache
# This ensures models downloaded by vllm/transformers are saved to /workspace
export HF_HOME=$HF_CACHE_DIR
export TRANSFORMERS_CACHE=$HF_CACHE_DIR
export HF_DATASETS_CACHE=$HF_CACHE_DIR
EOF

    # ------------------------------------------------------------------------------
    # 5. Update ~/.bashrc to Source the Persistent Setup
    # ------------------------------------------------------------------------------
    echo ">>> Updating $BASHRC_FILE to source environment setup..."
    SOURCE_LINE="source $ENV_SETUP_SCRIPT"

    # Check if the line already exists to avoid duplicates on re-runs
    if ! grep -qF "$SOURCE_LINE" "$BASHRC_FILE"; then
        echo "$SOURCE_LINE" >> "$BASHRC_FILE"
        echo "    Added source command to $BASHRC_FILE"
    else
        echo "    Source command already exists in $BASHRC_FILE"
    fi

    # ------------------------------------------------------------------------------
    # 6. Apply Changes Immediately
    # ------------------------------------------------------------------------------
    echo ">>> Applying environment changes to current session..."
    source $BASHRC_FILE

    # CRITICAL: Clear bash command cache so it finds newly installed binaries
    # This is required every time the container starts
    hash -r

    echo ">>> Environment applied and command cache cleared."

    # ------------------------------------------------------------------------------
    # 7. Downloading Models (Run Only If Not Exists)
    # ------------------------------------------------------------------------------
    if [ -d "$MODEL_DIR" ]; then
        echo ">>> Models already present at $MODEL_DIR. Skipping download..."
    else
        echo ">>> Pulling models to $HF_CACHE_DIR..."
        # Use python -m to ensure we use the newly installed package regardless of PATH
        python -m huggingface_hub.commands.huggingface_cli download datalab-to/chandra
        echo ">>> Model download complete."
    fi

    # ------------------------------------------------------------------------------
    # 9. Create vllm server script for ChandraOC
    # ------------------------------------------------------------------------------
    cat > $CHANDRA_SERVER_SCRIPT << EOF
python -m vllm.entrypoints.openai.api_server \
    --model datalab-to/chandra \
    --gpu-memory-utilization 0.9 \
    --max-model-len 16384 \
    --max-num-batched-tokens 32768 \
    --max-num-seqs 32 \
    --dtype bfloat16 \
    --tensor-parallel-size 2 \
    --distributed-executor-backend ray \
    --nnodes 1 \
    --no-enforce-eager \
    --host 0.0.0.0 \
    --port 8080 \
    --api-key "$VLLM_API_SECRET"
EOF
    chmod +x $CHANDRA_SERVER_SCRIPT

    # ------------------------------------------------------------------------------
    # 10. Verification
    # ------------------------------------------------------------------------------
    echo ">>> Provisioning complete!"
    echo "    Packages installed in: $PYTHON_DIR"
    echo "    Model cache configured at: $HF_CACHE_DIR"
    echo ""
    echo "    To verify PyTorch:"
    echo "    python -c 'import torch; print(torch.__version__)'"
    echo ""
    echo "    To verify vLLM:"
    echo "    vllm --version"
    echo ""
    echo "    To verify Hugging Face CLI:"
    echo "    huggingface-cli --version"

    touch "$BUILD_FLAG"
fi