#!/bin/bash

# ==============================================================================
# Vast.ai Persistent Provisioning Script
# ==============================================================================
# This script installs Python packages to /workspace/python-packages to ensure
# they persist across instance restarts when the volume is mounted.
# It also configures Hugging Face cache to persist models on /workspace.
# ==============================================================================

set -e  # Exit on error

# ------------------------------------------------------------------------------
# 1. Configuration & Paths
# ------------------------------------------------------------------------------
PYTHON_DIR="/workspace/python-packages"
HF_CACHE_DIR="/workspace/huggingface_cache"
ENV_SETUP_SCRIPT="/workspace/env_setup.sh"
BASHRC_FILE="$HOME/.bashrc"
# VLLM_API_SECRET="myscret" # should be passed on env vars during vast.ai build

# ------------------------------------------------------------------------------
# 2. Create Directories
# ------------------------------------------------------------------------------
echo ">>> Creating persistent directories..."
mkdir -p $PYTHON_DIR
mkdir -p $HF_CACHE_DIR

# ------------------------------------------------------------------------------
# 3. Install Python Packages | Pulls Models | Expects cuda-12
# ------------------------------------------------------------------------------
echo ">>> Installing packages to $PYTHON_DIR..."
echo "    (Using cu126 index as per Knowledge Base verification)"

pip install --target=$PYTHON_DIR \
    --ignore-installed \
    --no-cache-dir \
    --index-url https://pypi.org/simple/ \
    --extra-index-url https://download.pytorch.org/whl/cu126 \
    torch==2.10.0+cu126 \
    torchaudio==2.10.0+cu126 \
    torchvision==0.25.0+cu126 \
    torchcodec==0.10.0 \
    torchdata==0.10.0 \
    torchtext==0.6.0 \
    torch_c_dlpack_ext==0.1.5 \
    pillow==12.1.0 \
    chandra-ocr==0.1.8 \
    huggingface_hub==0.36.2 \
    vllm==0.17.1

# ------------------------------------------------------------------------------
# 4. Create Environment Setup Script
# ------------------------------------------------------------------------------
# This file lives on /workspace, so it persists across reboots.
# It sets PYTHONPATH, PATH, and HF_HOME.
# ------------------------------------------------------------------------------
echo ">>> Creating environment setup script at $ENV_SETUP_SCRIPT..."
cat > $ENV_SETUP_SCRIPT << EOF
# Auto-generated by provisioning_script.sh
# Persistent Environment Configuration

# 1. Python Packages Path
export PYTHONPATH=$PYTHON_DIR:\$PYTHONPATH
export PATH=$PYTHON_DIR/bin:\$PATH

# 2. Hugging Face & Model Cache
# This ensures models downloaded by vllm/transformers are saved to /workspace
export HF_HOME=$HF_CACHE_DIR
export TRANSFORMERS_CACHE=$HF_CACHE_DIR
export HF_DATASETS_CACHE=$HF_CACHE_DIR
EOF

# ------------------------------------------------------------------------------
# 5. Update ~/.bashrc to Source the Persistent Setup
# ------------------------------------------------------------------------------
echo ">>> Updating $BASHRC_FILE to source environment setup..."
SOURCE_LINE="source $ENV_SETUP_SCRIPT"

# Check if the line already exists to avoid duplicates on re-runs
if ! grep -qF "$SOURCE_LINE" "$BASHRC_FILE"; then
    echo "$SOURCE_LINE" >> "$BASHRC_FILE"
    echo "    Added source command to $BASHRC_FILE"
else
    echo "    Source command already exists in $BASHRC_FILE"
fi

# ------------------------------------------------------------------------------
# 6. Apply Changes Immediately
# ------------------------------------------------------------------------------
echo ">>> Applying environment changes to current session..."
source $BASHRC_FILE

# ------------------------------------------------------------------------------
# 7. Downloading models
# ------------------------------------------------------------------------------
echo ">>> Pulling models packages to $PYTHON_DIR..."
huggingface-cli download datalab-to/chandra

# ------------------------------------------------------------------------------
# 8. Verification
# ------------------------------------------------------------------------------
echo ">>> Provisioning complete!"
echo "    Packages installed in: $PYTHON_DIR"
echo "    Model cache configured at: $HF_CACHE_DIR"
echo ""
echo "    To verify PyTorch:"
echo "    python -c 'import torch; print(torch._version_)'"
echo ""
echo "    To verify vLLM:"
echo "    vllm --version"